added float serializer implementation and test
yahoo/Oak pull request #150
Opened 2021-03-22 16:33 UTC by NNRepos

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

* related to #138

2021-03-22 16:42 UTC, sanastas commented
Thank you for your contribution! We will review it on Wednesday.

2021-03-25 09:31 UTC, NNRepos commented
@sanastas, any updates?

2021-03-25 12:32 UTC, sanastas requested changes
Thank you! Looks good to me, small comments inside.

2021-03-25 12:32 UTC, sanastas commented on core/src/test/java/com/yahoo/oak/BuildAllTypes.java
> +        OakMapBuilder<Integer, Float> builder = new OakMapBuilder<Integer, Float>(int_comparator, int_serializer, float_serializer, Integer.MIN_VALUE)
Please make the line shorter

2021-03-25 12:32 UTC, sanastas commented on core/src/test/java/com/yahoo/oak/BuildAllTypes.java
> +    Assert.assertTrue(oak.get(my_key)==my_val);
Please add a check for new float comparator as well

2021-03-25 12:32 UTC, sanastas commented on core/src/test/java/com/yahoo/oak/BuildAllTypes.java
> +    // TODO add all type combinations
Is it possible to add some other types as well? Maybe just part of them...

2021-03-25 12:34 UTC, sanastas commented
> @sanastas, any updates?

@NNRepos thank you! I have taken a look and it looks good. I left some small comments, please let me know what do you think. I also assume that all Oak tests pass successfully, right?

2021-03-25 16:24 UTC, NNRepos commented
@sanastas done. is this ok?

2021-03-25 16:30 UTC, sanastas commented
yes looks good

2021-03-25 16:38 UTC, sanastas commented
When I tried `mvn clean package` myself on your code, there are some code styling errors:

[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:1: Line does not match expected header line of '/*'. [Header]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:6: Extra separation in import group before 'com.yahoo.oak.common.floatnum.OakFloatComparator' [ImportOrder]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:6: Wrong order for 'com.yahoo.oak.common.floatnum.OakFloatComparator' import. [ImportOrder]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:9: Extra separation in import group before 'com.yahoo.oak.common.integer.OakIntSerializer' [ImportOrder]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:11: Wrong order for 'com.yahoo.oak.common.integer.OakIntComparator' import. [ImportOrder]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:15:23: Variable 'MEBIBYTE' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:19:26: Name 'int_serializer' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:20:26: Name 'int_serializer2' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:21:26: Name 'int_comparator' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:28:13: Name 'my_key' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:29:13: Name 'my_val' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:38:26: Name 'int_serializer' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:39:28: Name 'float_serializer' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:40:26: Name 'int_comparator' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:47:13: Name 'my_key' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:48:15: Name 'my_val' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:57:28: Name 'float_serializer' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:58:29: Name 'string_serializer' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:59:28: Name 'float_comparator' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:66:15: Name 'my_key' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:67:16: Name 'my_val' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]

Can you please fix it? Thank I will merge this PR

2021-03-25 19:17 UTC, NNRepos commented
@sanastas alright.
i've reformatted the file - both the tests and `mvn clean` worked for me

2021-03-26 16:23 UTC, sanastas commented
@NNRepos ,

Thank you! Still when I do `mvn clean package` I get one last check style error.

`[ERROR] /Users/anastas/WorkDesk/DRUIDS/otherOakRepos/Oak/core/src/test/java/com/yahoo/oak/BuildAllTypes.java:15: Extra separation in import group before 'org.junit.Assert' [ImportOrder]`

It appears to me `mvn clean` shows not the same results as `mvn clean package`. Anyway, please fix that and I will merge this PR.

2021-03-27 20:48 UTC, NNRepos commented
@sanastas done. i think my VScode only supports `mvn clean`, so i can't confirm that it worked

2021-03-27 20:51 UTC, NNRepos commented
also, i recommend adding a PR check in GitHub which runs `mvn clean package` automatically. I can open a new issue if you're interested.

2021-03-28 09:10 UTC, sanastas commented
> @sanastas done. i think my VScode only supports mvn clean, so i can't confirm that it worked

@NNRepos , thank you! I verified that all code style checks pass. However, I payed attention that your test didn't run automatically and this is because all test files must have names: *Test.java Please fix the file and class name. I did the change locally and saw that all is good after that fix.

> also, i recommend adding a PR check in GitHub which runs mvn clean package automatically. I can open a new issue if you're interested.

Of course, go ahead and open an issue. If you could add the PR check in GitHub by yourself it could be wonderful. Otherwise, please explain in the issue how to do it. Because I do not know :)

2021-03-28 16:46 UTC, NNRepos commented
@sanastas will do

2021-03-29 07:38 UTC, merged

2021-03-29 07:45 UTC, sanastas commented
@NNRepos ,

Congratulations! Your PR was the first to be merged as part of the Yahoo Hackathon! Thank you for your contribution! It would be great to continue collaboration!

Are you from Verizon Media?

2021-03-31 06:27 UTC, NNRepos commented
@sanastas thanks!
no, i'm from the technion.

2021-03-31 07:16 UTC, sanastas commented
@NNRepos , that is interesting, I have done all my degrees in Technion and lectured there many semesters including the last winter semester.

Would you be interested in any future collaboration? Is there any way to contact you other than writing a comment here?

2021-04-06 05:43 UTC, NNRepos commented
@sanastas not really, as i'm already employed 😅 
thanks again :)